package com.example.oct31oopspookyassignment;

import javafx.scene.image.Image;

public class ProjectEulerProblem2 extends ProjectRepository{

    public ProjectEulerProblem2() {
        super("Each new term in the Fibonacci sequence is generated by adding the previous two terms." +
                " By starting with 1 and 2, the first terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n" +
                "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."
                , new Image("file:////Users/emiliomaset/IdeaProjects/oct31oopSpookyAssignment/projectEulerProblem2Screenshot.png"));
    }

    public int solver() {
        int sum = 2; // account for first fib2 = 2 since we skip it in the checking
        int fib1 = 1;
        int fib2 = 2;
        int newFib = 0;

        while (newFib < 4000000) {
            if (newFib  % 2 == 0)
                sum += newFib;
            newFib = fib1 + fib2;
            fib1 = fib2;
            fib2 = newFib;
        }
        return sum;
    }
}
